spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aab
    username: root
    password: wntkfkd11!
  jpa:
    hibernate:
      ddl-auto: create  # 이 설정은 Hibernate가 테이블을 생성하지 않게 합니다.
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html

